name = "FastaProcessing"
uuid = "de66c888-837f-4fc2-970e-50ef1f23b193"
authors = ["Shane Kuei-Hsien Chu (skchu@wustl.edu)"]
version = "1.0.0-DEV"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SeqShuffle = "5ea955a8-74dc-49b5-be65-6ee01fc504f7"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
